name: Publish

on:
  push:
    branches: [ master ]
    
jobs:
  pack:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: papeloto/action-zip@v1
      with:
        files: background.js manifest.json options.html options.js
        dest: billbee-zakeke.zip

    - uses: actions/upload-artifact@v2
      with:
        name: billbee-zakeke
        path: ./billbee-zakeke.zip
